name: flutter_splashscreen
description: Flutter splashscreen widget
version: 0.0.1
homepage: https://github.com/Iconica-Development/flutter_splashscreen

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  args: ^2.3.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
